"""
Run FHE GAT encoder on a graph loaded from file.
Supports .npz files generated by generate_graph.py.
"""

import argparse
import sys
import time
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

import numpy as np

from gat_encoder import gat_forward_plain
from gat_encoder_fhe import (
    GATEncoderFHE,
    FHEGraph,
    GATRunConfig,
    run_gat_pipeline,
    openfhe_available,
    openfhe_import_error,
)


def load_graph(graph_path: str):
    """Load graph from .npz file."""
    if not Path(graph_path).exists():
        raise FileNotFoundError(f"Graph file not found: {graph_path}")
    
    data = np.load(graph_path)
    
    if 'node_features' not in data or 'edge_index' not in data:
        raise ValueError(f"Graph file must contain 'node_features' and 'edge_index' arrays")
    
    node_features = data['node_features']
    edge_index = data['edge_index']
    
    return node_features, edge_index


def print_graph_stats(node_features, edge_index):
    """Print graph statistics."""
    num_nodes = node_features.shape[0]
    num_edges = edge_index.shape[1]
    in_channels = node_features.shape[1]
    
    in_degrees = np.bincount(edge_index[1], minlength=num_nodes)
    out_degrees = np.bincount(edge_index[0], minlength=num_nodes)
    
    print(f"\n{'='*60}")
    print(f"Loaded Graph Statistics")
    print(f"{'='*60}")
    print(f"Nodes:           {num_nodes}")
    print(f"Edges:           {num_edges}")
    print(f"Input features:  {in_channels}")
    print(f"Node features shape: {node_features.shape}")
    print(f"Edge index shape:    {edge_index.shape}")
    print(f"\nDegree statistics:")
    print(f"  Avg in-degree:  {in_degrees.mean():.2f}")
    print(f"  Avg out-degree: {out_degrees.mean():.2f}")
    print(f"  Max in-degree:  {in_degrees.max()}")
    print(f"  Max out-degree: {out_degrees.max()}")
    print(f"  Isolated nodes: {np.sum((in_degrees == 0) & (out_degrees == 0))}")
    print(f"{'='*60}\n")


def run_plaintext_encoder(node_features, edge_index, W, a, negative_slope=0.2):
    """Run plaintext GAT encoder for reference."""
    print("\n" + "="*60)
    print("Running Plaintext GAT Encoder (Reference)")
    print("="*60)
    
    start_time = time.time()
    output_plain = gat_forward_plain(node_features, edge_index, W, a, negative_slope)
    elapsed = time.time() - start_time
    
    print(f"Output shape: {output_plain.shape}")
    print(f"Output stats:")
    print(f"  Min:  {output_plain.min():.6f}")
    print(f"  Max:  {output_plain.max():.6f}")
    print(f"  Mean: {output_plain.mean():.6f}")
    print(f"  Std:  {output_plain.std():.6f}")
    print(f"Time: {elapsed:.3f}s")
    print("="*60)
    
    return output_plain


def run_fhe_encoder(
    node_features,
    edge_index,
    out_channels,
    W,
    a,
    negative_slope=0.2,
    batch_size=4,
    mult_depth=12,
    scale_mod_size=40,
    use_cggi=False,
    step1_linear: str = "enc",
    step2_attention: str = "enc",
    step3_leakyrelu: str = "enc",
    step4_softmax: str = "enc",
    step5_aggregation: str = "enc",
):
    """Run FHE GAT encoder."""
    num_nodes = node_features.shape[0]
    in_channels = node_features.shape[1]
    
    print("\n" + "="*60)
    print("Running FHE GAT Encoder")
    print("="*60)
    # Ensure batch_size is large enough for in_channels
    original_batch_size = batch_size
    if batch_size < in_channels:
        # Round up to nearest power of 2 for efficiency
        batch_size = 2 ** int(np.ceil(np.log2(in_channels)))    
        print(f"⚠️  WARNING: batch_size ({original_batch_size}) < in_channels ({in_channels})")
        print(f"   Auto-adjusting batch_size to {batch_size}\n")
    
    print(f"FHE Parameters:")
    print(f"  batch_size:     {batch_size}")
    print(f"  mult_depth:     {mult_depth}")
    print(f"  scale_mod_size: {scale_mod_size}")
    print(f"  use_cggi:       {use_cggi}")
    print(f"  negative_slope: {negative_slope}")
    print()
    
    # Initialize encoder
    setup_start = time.time()
    encoder = GATEncoderFHE(
        in_channels=in_channels,
        out_channels=out_channels,
        negative_slope=negative_slope,
        batch_size=batch_size,
        mult_depth=mult_depth,
        scale_mod_size=scale_mod_size,
        use_cggi=use_cggi,
    )
    setup_time = time.time() - setup_start
    print(f"FHE setup time: {setup_time:.2f}s")
    
    # Set weights to match plaintext
    encoder._W = W
    encoder._a = a
    
    # Encrypt graph
    encrypt_start = time.time()
    graph = FHEGraph.from_plain_encrypted(
        num_nodes=num_nodes,
        in_channels=in_channels,
        edge_index=edge_index,
        node_features_plain=node_features,
        crypto_context=encoder.crypto_context,
        public_key=encoder.keys.publicKey,
        batch_size=batch_size,
    )
    encrypt_time = time.time() - encrypt_start
    print(f"Encryption time: {encrypt_time:.2f}s")
    
    # Run pipeline (per-step configurable, default all enc)
    forward_start = time.time()
    cfg = GATRunConfig(
        step1_linear=step1_linear,
        step2_attention=step2_attention,
        step3_leakyrelu=step3_leakyrelu,
        step4_softmax=step4_softmax,
        step5_aggregation=step5_aggregation,
        batch_size=batch_size,
        mult_depth=mult_depth,
        scale_mod_size=scale_mod_size,
        use_cggi=use_cggi,
        negative_slope=negative_slope,
        print_metrics=True,
    )
    output_fhe = run_gat_pipeline(encoder=encoder, graph=graph, cfg=cfg)
    forward_time = time.time() - forward_start
    
    print(f"FHE forward time: {forward_time:.2f}s")
    print(f"Total FHE time: {setup_time + encrypt_time + forward_time:.2f}s")
    print()
    print(f"Output shape: {output_fhe.shape}")
    print(f"Output stats:")
    print(f"  Min:  {output_fhe.min():.6f}")
    print(f"  Max:  {output_fhe.max():.6f}")
    print(f"  Mean: {output_fhe.mean():.6f}")
    print(f"  Std:  {output_fhe.std():.6f}")
    print("="*60)
    
    return output_fhe


def compare_outputs(output_plain, output_fhe):
    """Compare plaintext and FHE outputs."""
    print("\n" + "="*60)
    print("Plaintext vs FHE Comparison")
    print("="*60)
    
    diff = np.abs(output_fhe - output_plain)
    
    print(f"Absolute difference:")
    print(f"  Min:  {diff.min():.6f}")
    print(f"  Max:  {diff.max():.6f}")
    print(f"  Mean: {diff.mean():.6f}")
    print(f"  Std:  {diff.std():.6f}")
    
    # Relative error
    rel_error = diff / (np.abs(output_plain) + 1e-10)
    print(f"\nRelative error:")
    print(f"  Mean: {rel_error.mean():.4f}")
    print(f"  Max:  {rel_error.max():.4f}")
    
    # Per-node comparison (first 5 nodes)
    num_display = min(5, output_plain.shape[0])
    print(f"\nPer-node comparison (first {num_display} nodes):")
    for i in range(num_display):
        plain_norm = np.linalg.norm(output_plain[i])
        fhe_norm = np.linalg.norm(output_fhe[i])
        node_diff = np.linalg.norm(output_fhe[i] - output_plain[i])
        print(f"  Node {i}: plain_norm={plain_norm:.4f}, fhe_norm={fhe_norm:.4f}, diff={node_diff:.4f}")
    
    print("="*60)


def save_output(output, output_path):
    """Save output to .npy file."""
    np.save(output_path, output)
    print(f"\nOutput saved to: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Run FHE GAT encoder on a graph file",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    
    # Required arguments
    parser.add_argument(
        'graph_file',
        type=str,
        help='Path to graph file (.npz format)',
    )
    parser.add_argument(
        '-o', '--out-features',
        type=int,
        required=True,
        help='Output feature dimension',
    )
    
    # FHE parameters
    parser.add_argument(
        '--batch-size',
        type=int,
        default=4,
        help='CKKS batch size (slots per ciphertext)',
    )
    parser.add_argument(
        '--mult-depth',
        type=int,
        default=12,
        help='Multiplicative depth (higher = more operations, more memory)',
    )
    parser.add_argument(
        '--scale-mod-size',
        type=int,
        default=40,
        help='Scaling modulus size in bits',
    )
    parser.add_argument(
        '--use-cggi',
        action='store_true',
        help='Enable CGGI scheme switching for encrypted LeakyReLU (requires more depth)',
    )

    # Per-step encryption modes (default all enc)
    for step_name in ["linear", "attention", "leakyrelu", "softmax", "aggregation"]:
        parser.add_argument(
            f"--{step_name}",
            choices=["enc", "dec"],
            default="enc",
            help=f"{step_name} step mode: enc (encrypted) or dec (plaintext)",
        )
    parser.add_argument(
        '--negative-slope',
        type=float,
        default=0.2,
        help='LeakyReLU negative slope',
    )
    
    # Other options
    parser.add_argument(
        '-s', '--seed',
        type=int,
        default=42,
        help='Random seed for weight initialization',
    )
    parser.add_argument(
        '--skip-plaintext',
        action='store_true',
        help='Skip plaintext reference computation',
    )
    parser.add_argument(
        '--save-output',
        type=str,
        default=None,
        help='Path to save FHE output (.npy file)',
    )
    
    args = parser.parse_args()
    
    # Check OpenFHE availability
    if not openfhe_available():
        print("ERROR: OpenFHE Python is not installed.")
        err = openfhe_import_error()
        if err:
            print(f"Import error: {err}")
        print("\nInstall with: pip install openfhe")
        print("Supported platforms: Ubuntu 22.04, 24.04")
        print("See: https://github.com/openfheorg/openfhe-python#installing-using-pip-for-ubuntu")
        sys.exit(1)
    
    # Load graph
    print(f"Loading graph from: {args.graph_file}")
    try:
        node_features, edge_index = load_graph(args.graph_file)
    except Exception as e:
        print(f"ERROR loading graph: {e}")
        sys.exit(1)
    
    print_graph_stats(node_features, edge_index)
    
    # Initialize weights
    in_channels = node_features.shape[1]
    np.random.seed(args.seed)
    W = np.random.randn(args.out_features, in_channels).astype(np.float64) * 0.1
    a = np.random.randn(2 * args.out_features).astype(np.float64) * 0.1
    
    print(f"Initialized weights:")
    print(f"  W: {W.shape}")
    print(f"  a: {a.shape}")
    print(f"  Seed: {args.seed}")
    
    # Run plaintext encoder (reference)
    output_plain = None
    if not args.skip_plaintext:
        output_plain = run_plaintext_encoder(
            node_features,
            edge_index,
            W,
            a,
            args.negative_slope,
        )
    
    # Run FHE encoder
    output_fhe = run_fhe_encoder(
        node_features,
        edge_index,
        args.out_features,
        W,
        a,
        negative_slope=args.negative_slope,
        batch_size=args.batch_size,
        mult_depth=args.mult_depth,
        scale_mod_size=args.scale_mod_size,
        use_cggi=args.use_cggi,
        step1_linear=args.linear,
        step2_attention=args.attention,
        step3_leakyrelu=args.leakyrelu,
        step4_softmax=args.softmax,
        step5_aggregation=args.aggregation,
    )
    
    # Compare outputs
    if output_plain is not None:
        compare_outputs(output_plain, output_fhe)
    
    # Save output if requested
    if args.save_output:
        save_output(output_fhe, args.save_output)
    
    print("\n✓ FHE GAT encoder completed successfully!")


if __name__ == "__main__":
    main()
